
# Cassandra Configuration
spring.cassandra.keyspace-name=church_products
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists

# Application Configuration
spring.application.name=Church Products API
server.port=8080
logging.level.org.springframework.data.cassandra=DEBUG
